version: '3.8'

services:
  cron_bot:
    build: .
    container_name: my_cron_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db
      - /etc/localtime:/etc/localtime:ro